### ISSUE TITLE
Error on Check for updates

### ISSUE THREAD

**Issue by Marlark** [AdyRock/com.community.store#11]
Upgraded to 3.0.0 and everytime i push Check for updates an error comes up. It just say Error and a OK button.

However if i push OK button on it after a while available updates from homeys app store comes up. Do not know if there is any updates from the community store sins all my apps is up to date from there.

Best Regards
Teddy

**Comment by AdyRock** [comment]
I have published a new version that should report any HCS errors as I think there are sometimes problems fetching the list of apps.
