### ISSUE TITLE
updates form community store arent shown. 

### ISSUE THREAD

**Issue by matrover** [AdyRock/com.community.store#4]
Hi, 

First, many thanks for this app i love it! 
i noticed that updates form the HCS arent shown anymore, is this know? 

i cant get my head around why this doenst work or firgure something out, but happy to help. 

Greetings, 
Matrover

**Comment by AdyRock** [comment]
OK, I was not aware of that.
I will look into ASAP.

**Comment by MaxvandeLaar** [comment]
@matrover I can name a few reasons, I changed the API responses and totally forgot to inform @AdyRock

**Comment by AdyRock** [comment]
Max has fixed the API so the HCS check should be working again now.

**Comment by matrover** [comment]
Yes works, thanks!
