### ISSUE TITLE
Homey app crashes if tapping on view of tado app update

### ISSUE THREAD

**Issue by matrover** [AdyRock/com.community.store#5]
see title. 

if tado has an update it shows below available updates, if you tap the view the whole homey app crashes.

maybe its because of the degrees symbol in the url https://homey.app/nl-nl/app/com.tado/tado%C2%B0/

**Comment by AdyRock** [comment]
Are you using version 0.0.9 of the app?

**Comment by matrover** [comment]
Yes and homey v5.0.1

Op 17 mrt. 2021 om 17:52 heeft Adrian Rockall ***@***.***> het volgende geschreven:

﻿

Are you using version 0.0.9 of the app?

**Comment by AdyRock** [comment]
I have published a new version. Hopefully this one will be OK.

**Comment by matrover** [comment]
Hi, there is an tado update it still crashes on V0.0.10

**Comment by AdyRock** [comment]
Doh, I switched off auto updates on tado but somehow I have go the latest version. I was hoping I could check it before updating.
I will have another hunt through the system.
