### ISSUE TITLE
Does not detect app updates

### ISSUE THREAD

**Issue by DeVisdude** [AdyRock/com.community.store#6]
I have the Nest app installed and it could not detect there was an update (already 3 versions behind).
Automatically as well as manually check failed. It simply says: no updates.
This is an example. This app also did not detect there was a newer version available of itself 0.0.08 -> 0.0.10
I already re-installed this app, but no luck.

**Comment by AdyRock** [comment]
Unfortunately the API for the Community Store is currently broken after the last store update. 
The app still works for the Athom store though.

**Comment by DeVisdude** [comment]
Thanks for the quick answer. Will that API be fixed anytime soon or is it over and done?

**Comment by AdyRock** [comment]
I'm not sure. I have talked to Max about it and he has said that it's not a quick fix. Basically the API is still looking in the old database so it needs to be updated to get the information from the new database. However, I believe the structure is different so it's not as simple as changing an address.

**Comment by AdyRock** [comment]
Max has fixed the API so the check for updates in the HCS should be working again now.

**Comment by DeVisdude** [comment]
Oh, that was fast! I have nothing to update right now, however I will monitor and let you know.
Maybe it is an idea to let the app show an error when it cannot connect to the API?

**Comment by MaxvandeLaar** [comment]
The app could always connect to the API, the api was just showing outdated data 😉
